xgb_10f.so: main.o tu0.o tu1.o tu10.o tu11.o tu12.o tu13.o tu14.o tu15.o tu16.o tu17.o tu18.o tu19.o tu2.o tu20.o tu21.o tu22.o tu23.o tu24.o tu25.o tu26.o tu27.o tu28.o tu29.o tu3.o tu30.o tu31.o tu4.o tu5.o tu6.o tu7.o tu8.o tu9.o
	gcc -shared -O3 -o xgb_10f.so main.o tu0.o tu1.o tu10.o tu11.o tu12.o tu13.o tu14.o tu15.o tu16.o tu17.o tu18.o tu19.o tu2.o tu20.o tu21.o tu22.o tu23.o tu24.o tu25.o tu26.o tu27.o tu28.o tu29.o tu3.o tu30.o tu31.o tu4.o tu5.o tu6.o tu7.o tu8.o tu9.o -std=c99 
main.o: main.c
	gcc -c -O3 -o main.o main.c -fPIC -std=c99 
tu0.o: tu0.c
	gcc -c -O3 -o tu0.o tu0.c -fPIC -std=c99 
tu1.o: tu1.c
	gcc -c -O3 -o tu1.o tu1.c -fPIC -std=c99 
tu10.o: tu10.c
	gcc -c -O3 -o tu10.o tu10.c -fPIC -std=c99 
tu11.o: tu11.c
	gcc -c -O3 -o tu11.o tu11.c -fPIC -std=c99 
tu12.o: tu12.c
	gcc -c -O3 -o tu12.o tu12.c -fPIC -std=c99 
tu13.o: tu13.c
	gcc -c -O3 -o tu13.o tu13.c -fPIC -std=c99 
tu14.o: tu14.c
	gcc -c -O3 -o tu14.o tu14.c -fPIC -std=c99 
tu15.o: tu15.c
	gcc -c -O3 -o tu15.o tu15.c -fPIC -std=c99 
tu16.o: tu16.c
	gcc -c -O3 -o tu16.o tu16.c -fPIC -std=c99 
tu17.o: tu17.c
	gcc -c -O3 -o tu17.o tu17.c -fPIC -std=c99 
tu18.o: tu18.c
	gcc -c -O3 -o tu18.o tu18.c -fPIC -std=c99 
tu19.o: tu19.c
	gcc -c -O3 -o tu19.o tu19.c -fPIC -std=c99 
tu2.o: tu2.c
	gcc -c -O3 -o tu2.o tu2.c -fPIC -std=c99 
tu20.o: tu20.c
	gcc -c -O3 -o tu20.o tu20.c -fPIC -std=c99 
tu21.o: tu21.c
	gcc -c -O3 -o tu21.o tu21.c -fPIC -std=c99 
tu22.o: tu22.c
	gcc -c -O3 -o tu22.o tu22.c -fPIC -std=c99 
tu23.o: tu23.c
	gcc -c -O3 -o tu23.o tu23.c -fPIC -std=c99 
tu24.o: tu24.c
	gcc -c -O3 -o tu24.o tu24.c -fPIC -std=c99 
tu25.o: tu25.c
	gcc -c -O3 -o tu25.o tu25.c -fPIC -std=c99 
tu26.o: tu26.c
	gcc -c -O3 -o tu26.o tu26.c -fPIC -std=c99 
tu27.o: tu27.c
	gcc -c -O3 -o tu27.o tu27.c -fPIC -std=c99 
tu28.o: tu28.c
	gcc -c -O3 -o tu28.o tu28.c -fPIC -std=c99 
tu29.o: tu29.c
	gcc -c -O3 -o tu29.o tu29.c -fPIC -std=c99 
tu3.o: tu3.c
	gcc -c -O3 -o tu3.o tu3.c -fPIC -std=c99 
tu30.o: tu30.c
	gcc -c -O3 -o tu30.o tu30.c -fPIC -std=c99 
tu31.o: tu31.c
	gcc -c -O3 -o tu31.o tu31.c -fPIC -std=c99 
tu4.o: tu4.c
	gcc -c -O3 -o tu4.o tu4.c -fPIC -std=c99 
tu5.o: tu5.c
	gcc -c -O3 -o tu5.o tu5.c -fPIC -std=c99 
tu6.o: tu6.c
	gcc -c -O3 -o tu6.o tu6.c -fPIC -std=c99 
tu7.o: tu7.c
	gcc -c -O3 -o tu7.o tu7.c -fPIC -std=c99 
tu8.o: tu8.c
	gcc -c -O3 -o tu8.o tu8.c -fPIC -std=c99 
tu9.o: tu9.c
	gcc -c -O3 -o tu9.o tu9.c -fPIC -std=c99 
